### ISSUE TITLE
Add `second` selector for arrays

### ISSUE THREAD

**Issue by badBlackShark** [oleander/remap#51]
There's already `first`, `last`, and `all`. For me, it would often be beneficial to also have a `second` selector. If you have two elements that need to be mapped differently, then using `last` also works -- unless the second element doesn't always exist.

So:
```rb
people = [{ name: 'Amy' }, { name: 'Bob' }]

get(:people, :first, :name) #=> 'Amy'
get(:people, :second, :name) #=> 'Bob'
get(:people, :last, :name) #=> 'Bob'

people = [{ name: 'Amy' }]

get(:people, :first, :name) #=> 'Amy'
get(:people, :second, :name) #=> nil
get(:people, :last, :name) #=> 'Amy'
```

Would it be possible to add something like this?

**Comment by oleander** [comment]
There's already the `at(index)`. Does that work?

**Comment by badBlackShark** [comment]
Oh really? So given my example I could do:
```rb
people = [{ name: 'Amy' }, { name: 'Bob' }]

get(:people, :first, :name) #=> 'Amy'
get(:people, at(1), :name) #=> 'Bob'

people = [{ name: 'Amy' }]

get(:people, :first, :name) #=> 'Amy'
get(:people, at(1), :name) #=> nil
```

That would indeed solve my problem. In that case, having `second` as syntax sugar would be neat imo, but not actually needed and probably not worth more than like 15 minutes of effort.

**Comment by oleander** [comment]
Yes, that should work. 

First and last are just syntax sugar for at(n). You can easily add "second" your self if you look at the code. It would be good practice if you want to extend the DSL in the future. Just make sure to add some tests if you decide to create a pull request ツ

**Comment by oleander** [comment]
Here's the logic: https://github.com/oleander/remap/blob/development/lib/remap/compiler.rb

**Comment by badBlackShark** [comment]
Oh yeah, that's actually very neat and should be easy. Well, thank you so much! I will consider this solved then! If I add it in the future, I'll make sure to make a PR :) Thank you for your help!
